wger/urls.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Workout Manager.  If not, see <http://www.gnu.org/licenses/>.

# Third Party
from django.conf import settings
from django.conf.urls import (
    include,
    url
)
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from rest_framework import routers
from tastypie.api import Api

# wger
from wger.core.api import (
    resources as core_api,
    views as core_api_views
)
from wger.exercises.api import (
    resources as exercises_api,
    views as exercises_api_views
)
from wger.exercises.sitemap import ExercisesSitemap
from wger.manager.api import (
    resources as manager_api,
    views as manager_api_views
)
from wger.nutrition.api import (
    resources as nutrition_api,
    views as nutrition_api_views
)
from wger.nutrition.sitemap import NutritionSitemap
from wger.utils.generic_views import (
    TextTemplateView,
    WebappManifestView
)
from wger.weight.api import (
    resources as weight_api,
    views as weight_api_views
)


admin.autodiscover()


#
# REST API
#

# /api/v1 - tastypie - deprecated
v1_api = Api(api_name='v1')

v1_api.register(exercises_api.ExerciseCategoryResource())
v1_api.register(exercises_api.ExerciseCommentResource())
v1_api.register(exercises_api.ExerciseImageResource())
v1_api.register(exercises_api.ExerciseResource())
v1_api.register(exercises_api.MuscleResource())
v1_api.register(exercises_api.EquipmentResource())

v1_api.register(nutrition_api.IngredientResource())
v1_api.register(nutrition_api.WeightUnitResource())
v1_api.register(nutrition_api.NutritionPlanResource())
v1_api.register(nutrition_api.MealResource())
v1_api.register(nutrition_api.MealItemResource())
v1_api.register(nutrition_api.IngredientToWeightUnit())

v1_api.register(manager_api.WorkoutResource())
v1_api.register(manager_api.ScheduleResource())
v1_api.register(manager_api.ScheduleStepResource())
v1_api.register(manager_api.DayResource())
v1_api.register(manager_api.SetResource())
v1_api.register(manager_api.SettingResource())
v1_api.register(manager_api.WorkoutLogResource())
v1_api.register(manager_api.WorkoutSessionResource())

v1_api.register(weight_api.WeightEntryResource())

v1_api.register(core_api.LanguageResource())
v1_api.register(core_api.DaysOfWeekResource())
v1_api.register(core_api.UserProfileResource())
v1_api.register(core_api.LicenseResource())


# /api/v2 - django rest framework
router = routers.DefaultRouter()

# Manager app
router.register(r'workout', manager_api_views.WorkoutViewSet, base_name='workout')
router.register(r'workoutsession', manager_api_views.WorkoutSessionViewSet, base_name='workoutsession')
router.register(r'schedulestep', manager_api_views.ScheduleStepViewSet, base_name='schedulestep')
router.register(r'schedule', manager_api_views.ScheduleViewSet, base_name='schedule')
router.register(r'day', manager_api_views.DayViewSet, base_name='day')
router.register(r'set', manager_api_views.SetViewSet, base_name='Set')
router.register(r'setting', manager_api_views.SettingViewSet, base_name='Setting')
router.register(r'workoutlog', manager_api_views.WorkoutLogViewSet, base_name='workoutlog')

# Core app
router.register(r'userprofile', core_api_views.UserProfileViewSet, base_name='userprofile')
router.register(r'language', core_api_views.LanguageViewSet, base_name='language')
router.register(r'daysofweek', core_api_views.DaysOfWeekViewSet, base_name='daysofweek')
router.register(r'license', core_api_views.LicenseViewSet, base_name='license')
router.register(r'setting-repetitionunit', core_api_views.RepetitionUnitViewSet, base_name='setting-repetition-unit')
router.register(r'setting-weightunit', core_api_views.WeightUnitViewSet, base_name='setting-weight-unit')

# Exercises app
# Add router for viewing exercise info
router.register(r'exerciseinfo', exercises_api_views.ExerciseInfoViewset, base_name='exerciseinfo')
router.register(r'exercise', exercises_api_views.ExerciseViewSet, base_name='exercise')
router.register(r'equipment', exercises_api_views.EquipmentViewSet, base_name='api')
router.register(r'exercisecategory', exercises_api_views.ExerciseCategoryViewSet, base_name='exercisecategory')
router.register(r'exerciseimage', exercises_api_views.ExerciseImageViewSet, base_name='exerciseimage')
router.register(r'exercisecomment', exercises_api_views.ExerciseCommentViewSet, base_name='exercisecomment')
router.register(r'muscle', exercises_api_views.MuscleViewSet, base_name='muscle')

# Nutrition app
router.register(r'ingredient', nutrition_api_views.IngredientViewSet, base_name='api-ingredient')
router.register(r'weightunit', nutrition_api_views.WeightUnitViewSet, base_name='weightunit')
router.register(r'ingredientweightunit', nutrition_api_views.IngredientWeightUnitViewSet, base_name='ingredientweightunit')
router.register(r'nutritionplan', nutrition_api_views.NutritionPlanViewSet, base_name='nutritionplan')
router.register(r'meal', nutrition_api_views.MealViewSet, base_name='meal')
router.register(r'mealitem', nutrition_api_views.MealItemViewSet, base_name='mealitem')

# Weight app
router.register(r'weightentry', weight_api_views.WeightEntryViewSet, base_name='weightentry')

#
# Sitemaps
#
sitemaps = {'exercises': ExercisesSitemap,
            'nutrition': NutritionSitemap}

#
# The actual URLs
#
urlpatterns = i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('wger.core.urls', namespace='core', app_name='core')),
    url(r'workout/', include('wger.manager.urls', namespace='manager')),
    url(r'exercise/', include('wger.exercises.urls', namespace='exercise')),
    url(r'weight/', include('wger.weight.urls', namespace='weight')),
    url(r'nutrition/', include('wger.nutrition.urls', namespace='nutrition')),
    url(r'software/', include('wger.software.urls', namespace='software', app_name='software')),
    url(r'config/', include('wger.config.urls', namespace='config', app_name='config')),
    url(r'gym/', include('wger.gym.urls', namespace='gym', app_name='gym')),
    url(r'email/', include('wger.email.urls', namespace='email')),
    url(r'^sitemap\.xml$',
        sitemap,
        {'sitemaps': sitemaps},
        name='sitemap')
)

#
# URLs without language prefix
#
urlpatterns += [
    url(r'^robots\.txt$',
        TextTemplateView.as_view(template_name="robots.txt"),
        name='robots'),
    url(r'^manifest\.webapp$', WebappManifestView.as_view(template_name="manifest.webapp")),
    url(r'^amazon-manifest\.webapp$', WebappManifestView.as_view(template_name="amazon-manifest.webapp")),

    # API
    url(r'^api/', include(v1_api.urls)),
    url(r'^api/v2/exercise/search/$',
        exercises_api_views.search,
        name='exercise-search'),
    url(r'^api/v2/exerciseinfo/search/$',
        exercises_api_views.search,
        name='exercise-info'),
    url(r'^api/v2/ingredient/search/$',
        nutrition_api_views.search,
        name='ingredient-search'),
    url(r'^api/v2/', include(router.urls)),
]

#
# URL for user uploaded files, served like this during development only
#
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wger/weight/urls.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Workout Manager.  If not, see <http://www.gnu.org/licenses/>.

# Third Party
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

# wger
from wger.weight import views
from wger.weight.forms import WeightCsvImportForm


urlpatterns = [
    url(r'^add/$',
        login_required(views.WeightAddView.as_view()),
        name='add'),

    url(r'^(?P<pk>\d+)/edit/$',
        login_required(views.WeightUpdateView.as_view()),
        name='edit'),

    url(r'^export-csv/$',
        views.export_csv,
        name='export-csv'),
    url(r'^import-csv/$',
        login_required(views.WeightCsvImportFormPreview(WeightCsvImportForm)),
        name='import-csv'),

    url(r'^overview/(?P<username>[\w.@+-]+)$',
        views.overview,
        name='overview'),
    # url(r'^overview/$',
    #     views.overview,
    #     name='overview'),
    url(r'^api/get_weight_data/(?P<username>[\w.@+-]+)$',  # JS
        views.get_weight_data,
        name='weight-data'),
    url(r'^api/get_weight_data/$',  # JS
        views.get_weight_data,
        name='weight-data'),
]

wger/weight/models.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Workout Manager.  If not, see <http://www.gnu.org/licenses/>.

# Third Party
from django.contrib.auth.models import User
from django.core.validators import (
    MaxValueValidator,
    MinValueValidator
)
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class WeightEntry(models.Model):
    '''
    Model for a weight point
    '''
    date = models.DateField(verbose_name=_('Date'))
    weight = models.DecimalField(verbose_name=_('Weight'),
                                 max_digits=5,
                                 decimal_places=2,
                                 validators=[MinValueValidator(30), MaxValueValidator(600)])
    user = models.ForeignKey(User,
                             verbose_name=_('User'))
    '''
    The user the weight entry belongs to.

    NOTE: this field is neither marked as editable false nor is it excluded in
    the form. This is done intentionally because otherwise it's *very* difficult
    and ugly to validate the uniqueness of unique_together fields and one field
    is excluded from the form. This does not pose any security risk because the
    value from the form is ignored and the request's user always used.
    '''

    class Meta:
        '''
        Metaclass to set some other properties
        '''
        verbose_name = _('Weight entry')
        ordering = ["date", ]
        get_latest_by = "date"
        unique_together = ("date", "user")

    def __str__(self):
        '''
        Return a more human-readable representation
        '''
        return u"{0}: {1:.2f} kg".format(self.date, self.weight)

    def get_owner_object(self):
        '''
        Returns the object that has owner information
        '''
        return self

wger/weight/forms.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License

# Third Party
from django import forms
from django.forms import (
    CharField,
    DateField,
    Form,
    ModelForm,
    Textarea,
    widgets
)
from django.utils.translation import ugettext as _

# wger
from wger.utils.constants import DATE_FORMATS
from wger.utils.widgets import Html5DateInput
from wger.weight.models import WeightEntry


CSV_DATE_FORMAT = (('%d.%m.%Y', 'DD.MM.YYYY (30.01.2012)'),
                   ('%d.%m.%y', 'DD.MM.YY (30.01.12)'),
                   ('%Y-%m-%d', 'YYYY-MM-DD (2012-01-30)'),
                   ('%y-%m-%d', 'YY-MM-DD (12-01-30)'),
                   ('%m/%d/%Y', 'MM/DD/YYYY (01/30/2012)'),
                   ('%m/%d/%y', 'MM/DD/YY (01/30/12)'),)


class WeightCsvImportForm(Form):
    '''
    A helper form with only a textarea
    '''
    csv_input = CharField(widget=Textarea, label=_('Input'))
    date_format = forms.ChoiceField(choices=CSV_DATE_FORMAT, label=_('Date format'))


class WeightForm(ModelForm):
    date = DateField(input_formats=DATE_FORMATS, widget=Html5DateInput())

    class Meta:
        model = WeightEntry
        exclude = []
        widgets = {
            'user': widgets.HiddenInput(),
        }

wger/weight/api/views.py
# -*- coding: utf-8 -*-

# This file is part of wger Workout Manager.
#
# wger Workout Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# wger Workout Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Workout Manager.  If not, see <http://www.gnu.org/licenses/>.

# Third Party
from rest_framework import viewsets

# wger
from wger.weight.api.serializers import WeightEntrySerializer
from wger.weight.models import WeightEntry


class WeightEntryViewSet(viewsets.ModelViewSet):
    '''
    API endpoint for nutrition plan objects
    '''
    serializer_class = WeightEntrySerializer
    is_private = True
    ordering_fields = '__all__'
    filter_fields = ('date',
                     'weight')

    def get_queryset(self):
        '''
        Only allow access to appropriate objects
        '''
        return WeightEntry.objects.filter(user=self.request.user)

    def perform_create(self, serializer):
        '''
        Set the owner
        '''
        serializer.save(user=self.request.user)

wger/weight/templates/import_csv_form.html
{% extends "base.html" %}
{% load wger_extras %}
{% load i18n %}

{% block title %}{% trans "Import weight logs" %}{% endblock %}

{% block content %}
<form action="{{form_action}}"
      method="post"
      class="form-horizontal">

    {% trans 'Submit' as submit_text %}
    {% render_form_fields form submit_text %}
</form>
{% endblock %}


{% block sidebar %}
<p>{% blocktrans %}Use this import field to import your weight logs into Workout
Manager.{% endblocktrans %}</p>

<p>{% blocktrans %}You can copy and paste from your spreadsheet into the text input,
the system will try to guess the format to import. The only things to consider is
that the first column is the <strong>date</strong>, the second the <strong>weight</strong>.
All further columns are ignored. There is a 1000 row limit.
{% endblocktrans %}</p>

<p>{% blocktrans %}If there are errors, you can correct or discard them in a
second step.{% endblocktrans %}</p>

{% endblock %}

wger/weight/templates/import_csv_preview.html
{% extends "base.html" %}
{% load wger_extras %}
{% load i18n %}

{% block title %}{% trans "Preview imported CSV entries" %}{% endblock %}



{% block content %}
<h4>{% trans "Successfully converted values" %}</h4>
<div class="alert alert-success">{% trans "The following values could be converted." %}</div>
<table class="table">
<tr>
    <th>{% trans "Date" %}</th>
    <th>{% trans "Weight" %}</th>
</tr>
{% for entry in weight_list %}
    <tr>
        <td>{{ entry.date|date:"SHORT_DATE_FORMAT" }}</td>
        <td>{{ entry.weight }}</td>
    </tr>
{% endfor %}
</table>



<h4>{% trans "Errors" %}</h4>

{% if error_list %}
    <div class="alert alert-danger">{% trans "The following values could not be converted." %}</div>

    <p>{% blocktrans %}These values could not be converted to a weight log entry.
    The reasons for this could be anything from an unrecognised date or number
    format, a problem with the encoding or something else. Please check that
    there are no obvious errors in the list (and correct them if there are!)
    and try to import the list again.{% endblocktrans %}</p>

    <p>{% blocktrans %}Remember that the expected structure is <strong>date</strong>
    on the first columns and <strong>weight</strong> on the second.{% endblocktrans %}</p>

    <table class="table">
    <tr>
        <th>{% trans "Date" %}</th>
        <th>{% trans "Weight" %}</th>
    </tr>
    {% for entry in error_list %}
        <tr>
            <td>{{ entry.0 }}</td>
            <td>{{ entry.1 }}</td>
        </tr>
    {% endfor %}
</table>

{% else %}
    <p>{% blocktrans %}There were no errors, all entries could be converted!{% endblocktrans %}</p>
{% endif %}


<h2>{% trans "Import all successfully converted entries" %}</h2>
<p>{% blocktrans %}Continue here if you want to import into your weight log all
entries that were successfully converted. All entries that produced an error
will simply be ignored. It's up to you to decide whether they are useful
(unrecognised entries) or not (e.g. headers, comments, etc.).{% endblocktrans %}</p>

<form action="{{form_action}}"
      method="post"
      class="form-horizontal">

    <input type="hidden" name="{{ stage_field }}" value="2" />
    <input type="hidden" name="{{ hash_field }}" value="{{ hash_value }}" />
    {% trans 'Import' as submit_text %}
    {% render_form_fields form submit_text %}
</form>



<h2>{% trans "Or try it again" %}</h2>

<p>{% blocktrans %}You can correct the list here and re-submit it as often as
you want.{% endblocktrans %}</p>

<form action="{{form_action}}"
      method="post"
      class="form">

    <input type="hidden" name="{{ stage_field }}" value="1" />
    {% trans 'Re-Submit' as submit_text %}
    {% render_form_fields form submit_text %}
</form>

{% endblock %}

wger/weight/templates/overview.html
{% extends "base.html" %}
{% load i18n staticfiles wger_extras %}

{#       #}
{# Title #}
{#       #}
{% block title %}{% trans "Weight overview" %}{% endblock %}

{#        #}
{# Header #}
{#        #}
{% block header %}
<script src="{% static 'js/weight.js' %}"></script>
{% endblock %}



{#         #}
{# Content #}
{#         #}
{% block content %}
<div id="current-username" data-current-username="{{ owner_user.username }}"></div>


{% if not min_date %}
<p>
    {% trans "There is no chart here because there are no weight entries." %}
    {% trans "Use link to add one." %}
</p>
{% endif %}

<div id="weight_diagram"></div>


<div class="btn-group modify-time-period-controls pull-right" role="group" aria-label="..." style="padding-bottom: 1em;">
    <button type="button" class="btn btn-default" data-time_period="90">{% trans "Last 3 months" %}</button>
    <button type="button" class="btn btn-default" data-time_period="365">{% trans "Last 12 months" %}</button>
    <button type="button" class="btn btn-default active" data-time_period="all">{% trans "No filter" %}</button>
</div>


{% if is_owner %}
{% if last_five_weight_entries_details %}
<table class="table">
    <tr>
        <th>{% trans 'Date' %}</th>
        <th>{% trans 'Weight' %}</th>
        <th>{% trans 'Change' context "Noun, not verb" %}</th>
        <th>{% trans 'Days' %}</th>
    </tr>
    {% for entry_detail in last_five_weight_entries_details %}
        <tr>
            <td>{{ entry_detail.0.date }}</td>
            <td>{{ entry_detail.0.weight }}</td>
            <!-- weight diff and day diff below -->
            <td>
                {% if entry_detail.1 > 0 %}
                    +
                {% endif %}
                {% if entry_detail.1 %}
                    {{ entry_detail.1 }}
                {% else %}
                    -/-
                {% endif %}
            </td>
            <td>
                {% if entry_detail.2 %}
                    {{ entry_detail.2 }}
                {% else %}
                    -/-
                {% endif %}
            </td>
        </tr>
    {% endfor %}
</table>
{% endif %}
{% endif %}

{% endblock %}


{#          #}
{# Side bar #}
{#          #}
{% block sidebar %}
{% endblock %}



{#         #}
{# Options #}
{#         #}
{% block options %}
{% if is_owner %}
<div class="btn-group">
    <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="{% fa_class 'cog' %}"></span>
        {% trans "Options" %}
    </button>
    <ul class="dropdown-menu">
        <li>
            <a href="{% url 'weight:export-csv' %}" target="_blank">
                <span class="{% fa_class 'download' %}"></span>
                {% trans "Export as CSV" %}
            </a>
        </li>
        <li>
            <a href="{% url 'weight:import-csv' %}" {% auto_link_css flavour %}>
                <span class="{% fa_class 'upload' %}"></span>
                {% trans "Import from spreadsheet" %}
            </a>
        </li>
    </ul>
</div>
<a href="{% url 'weight:add' %}" class="btn btn-success btn-sm wger-modal-dialog">
    {% trans "Add" %}
</a>
{% endif %}
{% endblock %}

wger/weight/templates/weight_overview.html
{% extends "base.html" %}
{% load i18n staticfiles wger_extras %}

<!--
        Title
-->
{% block title %}{% trans "Weight overview" %}{% endblock %}

<!--
        Header data
-->
{% block header %}
<script type="text/javascript">
$(document).ready(function () {

    $.getJSON("/weight/api/get_weight_data/{{ owner_user.username }}", function(json) {
        weight_chart(json, $('#content').width());
    });
});
</script>
{% endblock %}


<!--
        Main Content
-->
{% block content %}
{% if not min_date %}
<p>
    {% trans "There is no chart here because there are no weight entries." %}
    {% trans "Use link to add one." %}
</p>
{% endif %}

<div id="weight_diagram"></div>

{% if is_owner %}
{% if last_five_weight_entries_details %} 
<table class="table">
    <tr>  
        <th>{% trans 'Date' %}</th>
        <th>{% trans 'Weight' %}</th>
        <th>{% trans 'Change' context "Noun, not verb" %}</th>
        <th>{% trans 'Days' %}</th>
    </tr>
    {% for entry_detail in last_five_weight_entries_details %}
        <tr>
            <td>{{ entry_detail.0.date }}</td>
            <td>{{ entry_detail.0.weight }}</td>
            <!-- weight diff and day diff below -->
            <td>
                {% if entry_detail.1 > 0 %}
                    +
                {% endif %}
                {% if entry_detail.1 %}
                    {{ entry_detail.1 }}
                {% else %}
                    -/-
                {% endif %}
            </td>
            <td>
                {% if entry_detail.2 %} 
                    {{ entry_detail.2 }}
                {% else %}
                    -/-
                {% endif %}
            </td>
        </tr>
    {% endfor %}
</table>
{% endif %}
<br/>

<p>
    <em>{% trans "You can click on a value on the chart to edit it. "%}</em>
</p>
{% endif %}

{% endblock %}


<!--
        Side bar
-->
{% block sidebar %}
<p>
    <a href="{% url 'weight:add' %}" class="btn btn-success btn-sm wger-modal-dialog">
        {% trans "Add weight entry" %}
    </a>
</p>


<h4>{% trans "Filter options" %}</h4>
<p>{% blocktrans %}
Use the second chart to pan or zoom by clicking and dragging the selection. Clicking
on the background resets it.
{% endblocktrans %}</p>


{% if is_owner %}
<h4>{% trans "Options" %}</h4>
<p>
    <a href="{% url 'weight:export-csv' %}"
       target="_blank"
       {% auto_link_css flavour %}>
    <img src="{% static 'images/icons/save.svg' %}"
         width="32"
         height="32"
         alt="{% trans 'Export as CSV' %}"
         title="{% trans 'Export as CSV' %}">
        {% trans "Export as CSV" %}
    </a>
</p>

<p>
    <a href="{% url 'weight:import-csv' %}" {% auto_link_css flavour %}>
    <img src="{% static 'images/icons/csv-table.svg' %}"
         width="32"
         height="32"
         alt="{% trans 'Import from spreadsheet' %}"
         title="{% trans 'Import from spreadsheet' %}">
        {% trans "Import from spreadsheet" %}
    </a>
</p>
{% endif %}

{% endblock %}